name: lgldnet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.15
  - pip=24.2
  - cudatoolkit=12.7
  - pytorch=2.5.1
  - torchvision=0.20.1
  - numpy==1.23.5
  - pip:
    - academictorrents==2.3.3
    - albumentations==2.0.8
    - clip==0.2.0
    - einops==0.8.1
    - imageio==2.36.0
    - imageio==2.37.0
    - kornia==0.7.1
    - matplotlib==3.8.4
    - more_itertools==10.8.0
    - natsort==7.1.1
    - nibabel==5.3.2
    - numpy==1.23.5
    - omegaconf==2.3.0
    - opencv_contrib_python==4.10.0.84
    - packaging==25.0
    - Pillow==11.3.0
    - pudb==2025.1
    - pytorch_lightning==1.4.2
    - PyYAML==6.0.2
    - PyYAML==6.0.2
    - Requests==2.32.5
    - scipy==1.11.2
    - setuptools==75.1.0
    - skimage==0.0
    - streamlit==1.49.1
    - tqdm==4.67.1
    - transformers==4.49.0
    - typing_extensions==4.15.0
    - visdom==0.2.4

    - -e git+https://github.com/CompVis/taming_transformers.git@master#egg=taming_transformers
    - -e .
